# version of docker compose
version: "3"

name: drizzle-rbac

services:
  db:
    image: postgres
    container_name: drizzle-rbac-db
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: drizzle-rbac
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dev", "-d", "drizzle-rbac"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3308:5432

  # GUI to manage db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  drizzle-rbac:
    driver: local
